adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.my_admin, name='my_admin'),
    path('products/read/', adminapp.ProductListView.as_view(), name='products'),
    path('products/read/category/<int:category_pk>', adminapp.ProductListView.as_view(), name='products_by_category'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/create/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/read/<int:pk>/', adminapp.UserDetailView.as_view(), name='user_read'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),
    path('categorys/read/', adminapp.CategoryListView.as_view(), name='categorys'),
    path('categorys/read/<int:pk>/', adminapp.CategoryDetailView.as_view(), name='category_read'),
    path('categorys/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categorys/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categorys/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),
]

authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp
app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/', authapp.edit, name='edit'),
    path('logout/', authapp.logout, name='logout'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path
from .views import add, remove, basket, edit


app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='index'),
    path('add/<int:product_pk>/', add, name='add'),
    path('remove/<int:product_pk>/', remove, name='remove'),
    path('edit/<int:pk>/', edit, name='edit')

]

fishshop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from mainapp.views import main, catalog, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', main, name='main'),
    path('contacts/', contacts, name='contacts'),
    path('catalog/', catalog, name='catalog'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('admin/', admin.site.urls),
    path('auth/verify', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
from mainapp.views import catalog, product

app_name = 'mainapp'

urlpatterns = [
    path('category/', catalog, name='index'),
    path('category/<int:pk>', catalog, name='category'),
    path('product/<int:pk>', product, name='product')
]

ordersapp/urls.py
from django.urls import path, re_path
import ordersapp.views as ordersapp


app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),
    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(),
           name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(),
           name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(),
           name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(),
           name='order_delete'),


]

mainapp/models.py
from django.db import models

# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_hot = models.BooleanField(verbose_name='горячий продукт', default=False)
    is_active = models.BooleanField(verbose_name='активен', default=True, db_index=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @classmethod
    def get_items(cls):
        return cls.objects.filter(is_active=True)

mainapp/views.py
from django.core.cache import cache
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import cache_page

from fishshop import settings
from .models import ProductCategory, Product


def main(request):
    return render(request, 'mainapp/main.html', context={'title': 'Главная'})


def contacts(request):
    return render(request, 'mainapp/contacts.html', context={'title': 'Контакты'})


@cache_page(3600)
def catalog(request, pk=None):
    title = 'Каталог'
    products = Product.objects.all()
    category = ProductCategory.objects.all()
    if pk is None:
        hot_product = Product.objects.filter(is_hot=True).first()
        context = {
            'title': title,
            'hot_product': hot_product,
            'categories': category
        }
        return render(request, 'mainapp/hot_product.html', context)
    if pk > 0:
        products = products.filter(category=pk)
    content = {
        'title': title,
        'products': products,
        'categories': category,
    }
    return render(request, 'mainapp/catalog.html', content)


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def product(request, pk):
    # product = Product.objects.all()
    if pk:
        product = get_product(pk)
        title = product.name
    content = {
        'title': title,
        'product': product,
    }
    return render(request, 'mainapp/product.html', content)


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)

mainapp/templates/mainapp/includes/inc_basket_list.html
<table class="table">
        <thead>
            <tr>
                <th scope="col">Наименование товара</th>
                <th scope="col">Кол-во товара</th>
                <th scope="col">Цена</th>
            </tr>
        </thead>
        <tbody>
        {% for product in basket %}
            <tr>
                <td>{{product.product}}</td>
                <td><input type = "number" min="0"
                           name = {{product.product.pk}}
                           value="{{product.quantity}}">
                </td>
                <td>{{product.price}}</td>
                <td><button type="button" class="btn btn-light"><a href="{% url 'basket:remove' product.product.pk %}">Удалить</a></button></td>
            </tr>
        {% endfor %}
            <tr>
                <td>В общем</td>
                <td>{{total_quantity}}</td>
                <td>{{total_cost}}</td>
            </tr>
        </tbody>
</table>

mainapp/templates/mainapp/includes/inc_category_menu.html
<ul class="list-group list-group-horizontal">
    <li class="{% if request.resolver_match.kwargs.pk == category.pk or 0 %}
                  list-group-item list-group-item-action list-group-item-primary active
               {% else %}
                  list-group-item list-group-item-action list-group-item-primary
               {% endif %}">
        <a href="{% url 'catalog:category' 0 %}">Все</a>
    </li>
    {% for category in categories %}
        <li class="{% if request.resolver_match.kwargs.pk == category.pk %}
                  list-group-item list-group-item-action list-group-item-primary active
               {% else %}
                  list-group-item list-group-item-action list-group-item-primary
               {% endif %}">
            <a href="{% url 'catalog:category' category.pk %}">{{ category.name }}</a>
        </li>
    {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc_control.html
<div class="row">
        <ul class="list-group list-group-horizontal-md">
            {% if request.user.is_authenticated %}
                <li class="list-group-item"><a href="{% url 'ordersapp:orders_list' %}">Заказы</a></li>
                <li class="list-group-item"><a href="{% url 'auth:edit' %}">Редактировать</a></li>
                <li class="list-group-item"><a href="{% url 'auth:logout' %}">Выйти</a></li>
{#                <li class="list-group-item">#}
{#                    <div class="btn-group">#}
{#                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Action <span class="caret"></span></button>#}
{#                        <ul class="dropdown-menu">#}
{#                            <li><a href="#">Action</a></li>#}
{#                            <li><a href="#">Another action</a></li>#}
{#                            <li><a href="#">Something else here</a></li>#}
{#                        </ul>#}
{#                    </div>#}
{#                </li>#}
                    {% if request.user.is_superuser %}
                        <li class="list-group-item"><a href="{% url 'admin_custom:my_admin' %}">Админка</a></li>
                    {% endif %}
                <li class="list-group-item">Привет {{ request.user.username|title }}!</li>
            {% else %}
                <li class="list-group-item"><a href="{% url 'auth:login' %}">Войти</a></li>
                <li class="list-group-item"><a href="{% url 'auth:register' %}">Регистрация</a></li>
            {% endif %}
        </ul>
</div>

mainapp/templates/mainapp/includes/inc_foother.html
        <hr>
        <div class="foother">
                <p>Все права защищены&copy;</p>
        </div>

mainapp/templates/mainapp/includes/inc_menu.html
        <div class="header">
                <div class="header logo"><img src="/static/img/logo.png/" alt="logo"></div>
                <div class="header logo"><a href="{% url 'basket:index'%}"
                                    class="{% if request.resolver_match.url_name == 'main' %}
                                    current
                                    {% endif %}">
                                Корзина</a></div>
                    <div class="header menu_div">
                         <ul class="menu">
                             <li><a href="{% url 'main'%}"
                                    class="{% if request.resolver_match.url_name == 'main' %}
                                    current
                                    {% endif %}">
                                Главная</a></li>
                             <li><a href="{% url 'catalog'%}"
                                    class="{% if request.resolver_match.url_name == 'catalog' %}
                                    current
                                    {% endif %}">
                                 Каталог</a></li>
                             <li><a href="{% url 'contacts'%}"
                                    class="{% if request.resolver_match.url_name == 'contacts' %}
                                    current
                                    {% endif %}">
                                 Контакты</a></li>
                         </ul>
                    </div>
                </div>
        <hr>