adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.my_admin, name='my_admin'),
    path('products/read/', adminapp.ProductListView.as_view(), name='products'),
    path('products/read/category/<int:category_pk>', adminapp.ProductListView.as_view(), name='products_by_category'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/create/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/read/<int:pk>/', adminapp.UserDetailView.as_view(), name='user_read'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),
    path('categorys/read/', adminapp.CategoryListView.as_view(), name='categorys'),
    path('categorys/read/<int:pk>/', adminapp.CategoryDetailView.as_view(), name='category_read'),
    path('categorys/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categorys/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categorys/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),
]

authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp
app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/', authapp.edit, name='edit'),
    path('logout/', authapp.logout, name='logout'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

fishshop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from mainapp.views import main, catalog, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', main, name='main'),
    path('contacts/', contacts, name='contacts'),
    path('catalog/', catalog, name='catalog'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('admin/', admin.site.urls),
    path('auth/verify', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from django.views.generic.list import ListView
from mainapp.models import Product, ProductCategory
from authapp.models import ShopUser
from django.shortcuts import render
#from .forms import ProductAdminForm

class IsSuperUserView(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser

class ProductListView(IsSuperUserView, ListView):
    model = Product
    template_name = 'adminapp/products.html'
    queryset = Product.objects.all()

    def get_queryset(self):
        queryset = super(ProductListView, self).get_queryset()
        category_pk = self.kwargs.get('category_pk')
        if category_pk:
            category = get_object_or_404(ProductCategory, pk=category_pk)
            queryset = queryset.filter(category=category)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['title'] = 'Админка'
        context['categories'] = ProductCategory.objects.all()
        return context

class ProductDetailView(IsSuperUserView, DetailView):
    model = Product
    template_name = 'adminapp/product.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        title = Product.objects.get(pk=self.kwargs.get('pk')).name
        context['title'] = f'{title}. Админка'
        return context

class ProductCreateView(IsSuperUserView, CreateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    fields = '__all__'
    #success_url = reverse_lazy('admin_custom:products')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Создание нового продукта. Админка'
        return context

    def get_success_url(self):
        return reverse_lazy('admin_custom:product_read', kwargs={'pk':self.object.pk})

class ProductUpdateView(IsSuperUserView, UpdateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    fields = '__all__'
    success_url = reverse_lazy('admin_custom:products')

    def get_success_url(self):
        return reverse_lazy('admin_custom:product_read', kwargs={'pk':self.kwargs.get('pk')})

class ProductDeleteView(IsSuperUserView, DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'
    success_url = reverse_lazy('admin_custom:products')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductDeleteView, self).get_context_data(**kwargs)
        title = Product.objects.get(pk=self.kwargs.get('pk')).name
        context['title'] = 'Удаление {}. Админка'.format(title)
        return context

class UserListView(IsSuperUserView, ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    queryset = ShopUser.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context['title'] = 'Админка'
        return context

class UserDetailView(IsSuperUserView, DetailView):
    model = ShopUser
    template_name = 'adminapp/user.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super( UserDetailView, self).get_context_data(**kwargs)
        title = ShopUser.objects.get(pk=self.kwargs.get('pk')).username
        context['title'] = f'{title}. Админка'
        return context

class UserCreateView(IsSuperUserView, CreateView):
    model = ShopUser
    template_name = 'adminapp/product_update.html'
    fields = '__all__'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Создание нового пользователя. Админка'
        return context

    def get_success_url(self):
        return reverse_lazy('admin_custom:user_read', kwargs={'pk':self.object.pk})

class UserUpdateView(IsSuperUserView, UpdateView):
    model = ShopUser
    template_name = 'adminapp/product_update.html'
    fields = ['username', 'email', 'avatar', 'is_superuser']
    success_url = reverse_lazy('admin_custom:users')

    def get_success_url(self):
        return reverse_lazy('admin_custom:user_read', kwargs={'pk':self.kwargs.get('pk')})

class UserDeleteView(IsSuperUserView, DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('admin_custom:users')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserDeleteView, self).get_context_data(**kwargs)
        title = Product.objects.get(pk=self.kwargs.get('pk')).name
        context['title'] = 'Удаление {}. Админка'.format(title)
        return context

class CategoryListView(IsSuperUserView, ListView):
    model = ProductCategory
    template_name = 'adminapp/categorys.html'
    queryset = ProductCategory.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['title'] = 'Админка'
        return context

class CategoryDetailView(IsSuperUserView, DetailView):
    model = ProductCategory
    template_name = 'adminapp/category.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super( CategoryDetailView, self).get_context_data(**kwargs)
        title = ProductCategory.objects.get(pk=self.kwargs.get('pk')).name
        context['title'] = f'{title}. Админка'
        return context

class CategoryCreateView(IsSuperUserView, CreateView):
    model = ProductCategory
    template_name = 'adminapp/product_update.html'
    fields = '__all__'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Создание новой категории. Админка'
        return context

    def get_success_url(self):
        return reverse_lazy('admin_custom:category_read', kwargs={'pk':self.object.pk})

class CategoryUpdateView(IsSuperUserView, UpdateView):
    model = ProductCategory
    template_name = 'adminapp/product_update.html'
    fields = '__all__'
    success_url = reverse_lazy('admin_custom:categorys')

    def get_success_url(self):
        return reverse_lazy('admin_custom:category_read', kwargs={'pk':self.kwargs.get('pk')})

class CategoryDeleteView(IsSuperUserView, DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin_custom:categorys')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryDeleteView, self).get_context_data(**kwargs)
        title = Product.objects.get(pk=self.kwargs.get('pk')).name
        context['title'] = 'Удаление {}. Админка'.format(title)
        return context


def my_admin(request):
    return render(request, 'adminapp/my_admin.html', context={'title': 'Adminka'})

adminapp/templates/adminapp/base_admin.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    {% block css %}
    {% endblock %}
</head>
<body class="body">
    <div class="container">
        {% include 'adminapp/includes/inc_menu.html'%}

        {% block content %}{% endblock %}
        {% include 'mainapp/includes/inc_foother.html'%}
        {% block js %}{% endblock %}
    </div>
</body>
</html>

adminapp/templates/adminapp/category.html
{% extends 'adminapp/base_admin.html' %}
{% block content %}
<h1>{{object.name}}</h1>
<p>{{object.description}}</p>
<br>
<a href="{% url 'admin_custom:category_update' object.pk %}">Редактировать</a>
<br>
<a href="{% url 'admin_custom:category_delete' object.pk %}">Удалить</a>
<br>
<a href="{% url 'admin_custom:categorys' %}"> <-- Ко всем категориям</a>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base_admin.html' %}
{% block content %}
<div class="user_delete">
    Уверены, что хотите удалить {{ object.name }}?
    <form method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin_custom:categorys' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

adminapp/templates/adminapp/categorys.html
{% extends 'adminapp/base_admin.html' %}
{% block content %}
<div>
    <h3>Категории</h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item list-group-item-dark"><a href="{% url 'admin_custom:my_admin' %}">Назад в админку</a></li>
        <li class="list-group-item list-group-item-primary"><a href="{% url 'admin_custom:category_create' %}">Создать новую категорию</a></li>

    </ul>
    <br>
    <ul class="list-group list-group-flush">
        {% for objects in object_list %}
            <li class="list-group-item"><a href="{% url 'admin_custom:category_read' objects.pk %}">{{objects.name}}</a></li>
        {% endfor %}
    </ul>
    <br>

</div>
{% endblock %}

adminapp/templates/adminapp/my_admin.html
{% extends 'adminapp/base_admin.html' %}
{% block content %}
<br>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href="{% url 'admin_custom:users'  %}">Пользователи</a></li>

        <li class="list-group-item"><a href="{% url 'admin_custom:categorys' %}">Категории</a></li>

        <li class="list-group-item"><a href="{% url 'admin_custom:products' %}"> Продукты</a></li>
    </ul>
{% endblock %}

adminapp/templates/adminapp/product.html
{% extends 'adminapp/base_admin.html' %}
{% block content %}
<h1>{{object.name}}</h1>
<img src="/media/{{object.image}}/">
<p>{{ object.short_desc }}</p>
<br>
<a href="{% url 'admin_custom:product_update' object.pk %}">Редактировать</a>
<br>
<a href="{% url 'admin_custom:product_delete' object.pk %}">Удалить</a>
<br>
<a href="{% url 'admin_custom:products' %}"> <-- Ко всем продуктам</a>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base_admin.html' %}
{% block content %}
<div class="user_delete">
    Уверены, что хотите удалить {{ object.name }}?
    <form method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin_custom:products' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base_admin.html' %}
{% block content %}
<form class = "form-horizontal" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Применить">
</form>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base_admin.html' %}
{% block content %}
<div>
    <h3>Категории</h3>
    <ul class="list-group list-group-horizontal">
        <li class="{% if request.resolver_match.kwargs.pk == category.pk or 0 %}
                  list-group-item list-group-item-action list-group-item-primary active
               {% else %}
                  list-group-item list-group-item-action list-group-item-primary
               {% endif %}">
        <a href="{% url 'admin_custom:products_by_category' 0 %}">Все</a></li>
        {% for category in categories %}
        <li class="{% if request.resolver_match.kwargs.pk == category.pk %}
                  list-group-item list-group-item-action list-group-item-primary active
               {% else %}
                  list-group-item list-group-item-action list-group-item-primary
               {% endif %}">
        <a href="{% url 'admin_custom:products_by_category' category.pk %}">{{ category.name }}</a></li>

        {% endfor %}
    </ul>
    <h3>Товары</h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item list-group-item-dark"><a href="{% url 'admin_custom:my_admin' %}">Назад в админку</a></li>
        <li class="list-group-item list-group-item-primary"><a href="{% url 'admin_custom:product_create' %}">Создать новый подукт</a></li>
    </ul>
    <br>
    <ul class="list-group list-group-flush">
        {% for objects in object_list %}
            <li class="list-group-item"><a href="{% url 'admin_custom:product_read' objects.pk %}">{{objects.name}}</a></li>
        {% endfor %}
   </ul>

</div>
{% endblock %}

adminapp/templates/adminapp/user.html
{% extends 'adminapp/base_admin.html' %}
{% block content %}
<h1>{{object.username}}</h1>
<img src="/media/{{object.avatar}}/">
<p></p>
<br>
<a href="{% url 'admin_custom:user_update' object.pk %}">Редактировать</a>
<br>
<a href="{% url 'admin_custom:user_delete' object.pk %}">Удалить</a>
<br>
<a href="{% url 'admin_custom:users' %}"> <-- Ко всем пользователям</a>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base_admin.html' %}
{% block content %}
<div class="user_delete">
    Уверены, что хотите удалить {{ object.name }}?
    <form method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin_custom:users' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base_admin.html' %}
{% block content %}
<div>
    <h3>Пользователи</h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item list-group-item-dark"><a href="{% url 'admin_custom:my_admin' %}">Назад в админку</a></li>
        <li class="list-group-item list-group-item-primary"><a href="{% url 'admin_custom:user_create' %}">Создать нового пользователя</a></li>
   </ul>
    <br>
   <ul class="list-group list-group-flush">
       {% for objects in object_list %}
            <li class="list-group-item"><a href="{% url 'admin_custom:user_read' objects.pk %}">{{objects.username}}</a></li>
       {% endfor %}
   </ul>

</div>
{% endblock %}