authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp
app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/', authapp.edit, name='edit'),
    path('logout/', authapp.logout, name='logout'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path
from .views import add, remove, basket, edit


app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='index'),
    path('add/<int:product_pk>/', add, name='add'),
    path('remove/<int:product_pk>/', remove, name='remove'),
    path('edit/<int:pk>/', edit, name='edit')

]

fishshop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from mainapp.views import main, catalog, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', main, name='main'),
    path('contacts/', contacts, name='contacts'),
    path('catalog/', catalog, name='catalog'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('admin/', admin.site.urls),
    path('auth/verify', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
from mainapp.views import catalog, product

app_name = 'mainapp'

urlpatterns = [
    path('category/', catalog, name='index'),
    path('category/<int:pk>', catalog, name='category'),
    path('product/<int:pk>', product, name='product')
]

mainapp/models.py
from django.db import models

# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_hot = models.BooleanField(verbose_name='горячий продукт', default=False)
    is_active = models.BooleanField(verbose_name='активен', default=True, db_index=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @classmethod
    def get_items(cls):
        return cls.objects.filter(is_active=True)

mainapp/views.py
from django.core.cache import cache
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import cache_page

from fishshop import settings
from .models import ProductCategory, Product


def main(request):
    return render(request, 'mainapp/main.html', context={'title': 'Главная'})


def contacts(request):
    return render(request, 'mainapp/contacts.html', context={'title': 'Контакты'})


@cache_page(3600)
def catalog(request, pk=None):
    title = 'Каталог'
    products = Product.objects.all()
    category = ProductCategory.objects.all()
    if pk is None:
        hot_product = Product.objects.filter(is_hot=True).first()
        context = {
            'title': title,
            'hot_product': hot_product,
            'categories': category
        }
        return render(request, 'mainapp/hot_product.html', context)
    if pk > 0:
        products = products.filter(category=pk)
    content = {
        'title': title,
        'products': products,
        'categories': category,
    }
    return render(request, 'mainapp/catalog.html', content)


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def product(request, pk):
    # product = Product.objects.all()
    if pk:
        product = get_product(pk)
        title = product.name
    content = {
        'title': title,
        'product': product,
    }
    return render(request, 'mainapp/product.html', content)


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/npm.js' %}"></script>
    {% block css %}
    {% endblock %}
</head>
<body class="body">
    <div class="container">
        {% include 'mainapp/includes/inc_menu.html'%}
        {% include 'mainapp/includes/inc_control.html'%}
        {% block content %}{% endblock %}
        {% include 'mainapp/includes/inc_foother.html'%}
    </div>
</body>
</html>

mainapp/templates/mainapp/basket.html
{% extends 'mainapp/base.html' %}
{% load staticfiles%}
{% load custom_tags %}
{% block content %}
<div class="basket_list">
{% include 'mainapp/includes/inc_basket_list.html' %}
</div>
{% endblock %}

{% block js %}
    <script src="{% static 'js/basket_scripts.js' %}"></script>
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
{% endblock %}

mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% block content %}
<div class="catalog">
        <h1>Каталог</h1>
        {% include 'mainapp/includes/inc_category_menu.html' %}
        {% for product in products %}
            <div class="fish"><a href="{% url 'catalog:product' product.pk %}"><img src="/media/{{ product.image }}" height="150"><br>{{product.name}}</a></div>
        {% endfor %}

</div>
{% endblock %}

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% block content %}
<div>
    <form action="">
       <h3>Форма обратной связи</h3>
        Ваше имя <input type="text" placeholder="Name" size="20"  title="Введите ваше имя млм как к вам обращаться"><br>
        Email <input type="text" placeholder="Email@mail.com" size="24" class = "input_cl" title="Введите свой Email"><br>
        Текст <br>
        <textarea type="text" placeholder="Текст вашего обращения" cols="55" rows="5"></textarea>
        <br><br>
        <input type="submit" value="Отправить"> <input type="reset">
    </form>
    <h3> Наш адрес</h3>
    <p>г. Екатеринбург ул.Армавирская дом 18 офис 206</p>
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d1879.8533420308136!2d60.57819651370215!3d56.86458712647475!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2sru!4v1568547582896!5m2!1sru!2sru" width="100%" height="374" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
</div>
{% endblock %}

mainapp/templates/mainapp/hot_product.html
{% extends 'mainapp/base.html' %}
{% block content %}
<div class="catalog">
        <h1>Каталог</h1>
        {% include 'mainapp/includes/inc_category_menu.html' %}
            <h2>Горячее предложение!</h2>
            <div class="fish"><a href="{% url 'catalog:product' hot_product.pk %}"><img src="/media/{{ hot_product.image }}" height="150"><br>{{hot_product.name}}</a></div>


</div>
{% endblock %}

mainapp/templates/mainapp/main.html
{% extends 'mainapp/base.html' %}
{% block content %}
        <div class="content">
            <h1>Рыбосики</h1>
            <p>Добро пожаловать в магазин РЫБОСИКИ! Здесь вы можете купить РЫБОСИКОВ!</p>
        </div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load custom_tags %}
{% block content %}
    <div class ="product">
          <h1>{{ product.name }}</h1>
          <div class="image"><a href="" target="_blank"><img src="/media/{{ product.image }}" height="270" alt="ramirezi"></a></div>
          <h3 class="heading">Описание</h3>
          <p class="short_discription"> {{ product.short_desc }}</p>
          <div class="short_discription cost">{{ product.price }}</div>
          <a href="{% url 'basket:add' product.pk %}">Купить</a>
    </div>
    <div class="curve">
        <h3 class="heading">Характеристики</h3>
        <p class="discription">{{ product.description }}</p>
    </div>
{% endblock %}